version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
      - mkdir builds
      - cp cli/target/cli-1.0-jar-with-dependencies.jar builds/sokrates.jar
      - cp codeexplorer/target/codeexplorer-1.0-jar-with-dependencies.jar builds/sokrates-explorer.jar
      - cp builds/sokrates.jar builds/sokrates-0.9.jar
      - cp builds/sokrates-explorer.jar builds/sokrates-explorer-0.9.jar
artifacts:
  files:
    - builds/sokrates.jar
    - builds/sokrates-explorer.jar
    - builds/sokrates-0.9.jar
    - builds/sokrates-explorer-0.9.jar
